name: FliqIOS
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    TARGETED_DEVICE_FAMILY: "1,2"
    DEVELOPMENT_TEAM: "722J78K2H6"
    PRODUCT_NAME: Fliq iOS
    PRODUCT_BUNDLE_IDENTIFIER: com.fliq.ios
    CURRENT_PROJECT_VERSION: 5
    MARKETING_VERSION: 1.0
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 11.0.0
  RazorpayCheckout:
    url: https://github.com/razorpay/razorpay-pod.git
    from: 1.4.1
targets:
  FliqIOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    dependencies:
      - package: Firebase
        product: FirebaseCore
      - package: Firebase
        product: FirebaseMessaging
      - package: RazorpayCheckout
        product: RazorpayCheckout
    sources:
      - path: FliqIOS/Sources
    resources:
      - path: FliqIOS/Resources
    settings:
      base:
        INFOPLIST_FILE: FliqIOS/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: FliqIOS/FliqIOS.entitlements
        SUPPORTS_MACCATALYST: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        DEVELOPMENT_ASSET_PATHS: "\"FliqIOS/Preview Content\""
